require("user.options")
require("user.keymaps")
require("user.tagbar")
require("user.plugins")
require("user.colorscheme")
require("user.cmp")
require("user.lsp")
require("user.nvimtree")
require("user.telescope")
require("user.treesitter")
require("user.autopairs")
require("user.comment")
require("user.gitsigns")
require("user.bufferline")
require("user.toggleterm")
require("user.project")
require("user.impatient")
require("user.indentline")
require("user.alpha")
require("user.whichkey")
require("user.autocommands")
require("user.neogit")
require("user.dadbod")
require("user.tagbar")

-- require("user.chatgpt") -- in zshrc add [ -f "$HOME/.config/.openai_key.zsh" ] && source "$HOME/.config/.openai_key.zsh"
 
