-- Note: Exafunction/codeium.nvim was renamed to windsurf.nvim
-- Disabled: commenting out for now
-- return {
-- 	"Exafunction/windsurf.nvim",
-- 	dependencies = {
-- 		"nvim-lua/plenary.nvim",
-- 		"hrsh7th/nvim-cmp",
-- 	},
-- 	config = function()
-- 		require("codeium").setup({})
-- 	end,
-- }
return {}
