-- Disabled: noice.nvim handles notifications via its mini view (bottom-right).
-- This plugin conflicts by hijacking vim.notify before noice can route it.
-- return {
-- 	"rcarriga/nvim-notify",
-- 	enabled = true,
-- 	config = function()
-- 		require("notify").setup({
-- 			stages = "fade_in_slide_out",
-- 			timeout = 300,
-- 			render = "default",
-- 			max_width = 120,
-- 			max_height = 40,
-- 			background_colour = "#000000",
-- 			merge_duplicates = true,
-- 		})
-- 	end,
-- }
return {}
